language: python
os: linux
dist: trusty
sudo: true

matrix:
  include:
    # Clang 3.5
    - env: CXX=clang++-3.5 CC=clang-3.5
      addons: { apt: { packages: ["clang-3.5", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.5"] } }

    # Clang 3.6
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons: { apt: { packages: ["clang-3.6", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.6"] } }

    # Clang 3.7
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons: { apt: { packages: ["clang-3.7", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7"] } }

    # Clang 3.8
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons: { apt: { packages: ["clang-3.8", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"] } }

    # Clang 3.9
    - env: CXX=clang++-3.9 CC=clang-3.9
      addons: { apt: { packages: ["clang-3.9", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.9"] } }
    # Clang 4.0
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons: { apt: { packages: ["clang-4.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0"] } }
    # Clang 5.0
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons: { apt: { packages: ["clang-5.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }
    # GCC 4.9
    - env: CXX=g++-4.9  CC=gcc-4.9
      addons: { apt: { packages: ["g++-4.9", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }
    # GCC 5
    - env: CXX=g++-5  CC=gcc-5
      addons: { apt: { packages: ["g++-5", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }
    # GCC 6
    - env: CXX=g++-6  CC=gcc-6
      addons: { apt: { packages: ["g++-6", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }
    # GCC 7
    - env: CXX=g++-7  CC=gcc-7
      addons: { apt: { packages: ["g++-7", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }
      
script:
  - pip install conan --upgrade
  - conan user
  - conan install boost/1.66.0@conan/stable --build missing
  - ls -la
  - BOOST_ROOT="$(python boost_root.py)"
  - mkdir build && cd build
  - cmake .. -DBOOST_ROOT:PATH=$BOOST_ROOT -DBUILD_TESTS:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=install
  - cmake --build . --target install
